/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import CAT.CommonUtilityClass;
import CAT.ImageInfo;
import CAT.Main;
import Segmentation. Scale;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author amoghk
 */
public class GUI extends javax.swing.JFrame implements ItemListener {

    JFileChooser fileDialog;
    //File directory;
    StrengthImprovementCaptcha sic;
    //JComboBox websiteSelect;
    String website=null,recognizedCAPTCHA;
    boolean captchaPresent=false,guiFirst=true;
    Dimension imgSize,newDimensions = null;
    Dimension boundary = new Dimension(91,48);
    public File[] fList=new File[16];
    Scale s;
    Main m;
    boolean specimenLoaded=false;
    Image resizedImage;
    File file1=null;
    String path,historyPath;
    public static String extension;
    BufferedImage originalImage;//this image is in center
    BufferedImage his;//image is in history
    BufferedImage temp;
    BufferedImage scaledImage;//this image is scaled version of original image to fit in the JLabel image
    File listOfFiles[];
    ImageInfo imgInfo;
       //BufferedImage specimen[]=new BufferedImage[15];
      // public static BufferedImage captcha;
       
   
   /*
    * this constructor initialises all the objects used within the class
    */ 
    public GUI() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")).getScaledInstance(600,254, WIDTH));
        initComponents();
        imgInfo=new ImageInfo();
        //strengthImp.setEnabled(false);
        websiteSelect.setEditable(false);
        this.setResizable(false);
       
    }
   
//    public GUI(File file1,String website)
//    {
//        this.file1=file1;
//        this.website=website;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        image1 = new javax.swing.JLabel();
        breakAnalyze = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        websiteSelect = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        history = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        s1 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        s6 = new javax.swing.JLabel();
        s5 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        s9 = new javax.swing.JLabel();
        s8 = new javax.swing.JLabel();
        s7 = new javax.swing.JLabel();
        s10 = new javax.swing.JLabel();
        s15 = new javax.swing.JLabel();
        s14 = new javax.swing.JLabel();
        s13 = new javax.swing.JLabel();
        s12 = new javax.swing.JLabel();
        s11 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        img7 = new javax.swing.JLabel();
        img8 = new javax.swing.JLabel();
        img9 = new javax.swing.JLabel();
        img10 = new javax.swing.JLabel();
        img11 = new javax.swing.JLabel();
        img12 = new javax.swing.JLabel();
        img13 = new javax.swing.JLabel();
        img14 = new javax.swing.JLabel();
        img15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        image.setToolTipText("the loaded captcha");
        image.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        image.setName(""); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAPTCHA ANALYZER TOOL(CAT)");
        setBounds(new java.awt.Rectangle(300, 150, 0, 0));
        setName("MainPage"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s1MouseClicked(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        jPanel2.setBackground(java.awt.SystemColor.window);
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(529, 1000));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        image1.setBackground(new java.awt.Color(255, 255, 255));
        image1.setToolTipText("loaded Captcha");
        image1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        image1.setName(""); // NOI18N
        image1.setOpaque(true);
        image1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image1MouseClicked(evt);
            }
        });

        breakAnalyze.setText("BREAK AND ANALYZE");
        breakAnalyze.setToolTipText("Break the Captcha ");
        breakAnalyze.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        breakAnalyze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakAnalyzeActionPerformed(evt);
            }
        });

        jButton1.setText("BROWSE");
        jButton1.setToolTipText("Browse for more images");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Website Name:");

        websiteSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--------Select Website--------", "AADHAR", "BMACCESS", "CCAVENUE", "CEOMAHARASHTRA", "CITYALLY", "DOOSTANG", "EASYBM", "ESCHOLARSHIP", "FREEDNS", "GATE", "HOTMAIL", "INDIANEXPRESS", "IRCTC", "MSRCTC", "PCSTORE", "PIXELGROOVY", "SBI", "SHIKSHA", "SPEAKINGTREE", "TINYPIC", "VODAFONE", "WEBSPAMPROTECT", "WIKIPEDIA", "YEBHI", "AOLMAIL", "BOTDETECT" }));
        websiteSelect.setToolTipText("Select the website");
        websiteSelect.setBorder(null);
        websiteSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        websiteSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                websiteSelectItemStateChanged(evt);
            }
        });
        websiteSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(websiteSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(breakAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(websiteSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(breakAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel3.setBackground(java.awt.SystemColor.window);
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setText("HISTORY");

        history.setBackground(new java.awt.Color(255, 255, 255));
        history.setToolTipText("Previous Image");
        history.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history.setOpaque(true);
        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPanel4.setBackground(java.awt.SystemColor.window);
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setPreferredSize(new java.awt.Dimension(110, 1000));

        jButton4.setText("ABOUT US");
        jButton4.setToolTipText("More info about CAT developers\n");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jButton4.setBorderPainted(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("HELP");
        jButton2.setToolTipText("How to use CAT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(178, 4050));

        jPanel5.setBackground(java.awt.SystemColor.window);
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.setPreferredSize(new java.awt.Dimension(176, 2000));

        s1.setBackground(new java.awt.Color(255, 255, 255));
        s1.setToolTipText("load the specimen");
        s1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s1.setOpaque(true);
        s1.setPreferredSize(new java.awt.Dimension(91, 48));
        s1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s1MouseClicked(evt);
            }
        });

        s3.setBackground(new java.awt.Color(255, 255, 255));
        s3.setToolTipText("load the specimen");
        s3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s3.setOpaque(true);
        s3.setPreferredSize(new java.awt.Dimension(91, 48));
        s3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s3MouseClicked(evt);
            }
        });

        s2.setBackground(new java.awt.Color(255, 255, 255));
        s2.setToolTipText("load the specimen");
        s2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s2.setOpaque(true);
        s2.setPreferredSize(new java.awt.Dimension(91, 48));
        s2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s2MouseClicked(evt);
            }
        });

        s6.setBackground(new java.awt.Color(255, 255, 255));
        s6.setToolTipText("load the specimen");
        s6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s6.setOpaque(true);
        s6.setPreferredSize(new java.awt.Dimension(91, 48));
        s6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s6MouseClicked(evt);
            }
        });

        s5.setBackground(new java.awt.Color(255, 255, 255));
        s5.setToolTipText("load the specimen");
        s5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s5.setOpaque(true);
        s5.setPreferredSize(new java.awt.Dimension(91, 48));
        s5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s5MouseClicked(evt);
            }
        });

        s4.setBackground(new java.awt.Color(255, 255, 255));
        s4.setToolTipText("load the specimen");
        s4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s4.setOpaque(true);
        s4.setPreferredSize(new java.awt.Dimension(91, 48));
        s4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s4MouseClicked(evt);
            }
        });

        s9.setBackground(new java.awt.Color(255, 255, 255));
        s9.setToolTipText("load the specimen");
        s9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s9.setOpaque(true);
        s9.setPreferredSize(new java.awt.Dimension(91, 48));
        s9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s9MouseClicked(evt);
            }
        });

        s8.setBackground(new java.awt.Color(255, 255, 255));
        s8.setToolTipText("load the specimen");
        s8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s8.setOpaque(true);
        s8.setPreferredSize(new java.awt.Dimension(91, 48));
        s8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s8MouseClicked(evt);
            }
        });

        s7.setBackground(new java.awt.Color(255, 255, 255));
        s7.setToolTipText("load the specimen");
        s7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s7.setOpaque(true);
        s7.setPreferredSize(new java.awt.Dimension(91, 48));
        s7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s7MouseClicked(evt);
            }
        });

        s10.setBackground(new java.awt.Color(255, 255, 255));
        s10.setToolTipText("load the specimen");
        s10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s10.setOpaque(true);
        s10.setPreferredSize(new java.awt.Dimension(91, 48));
        s10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s10MouseClicked(evt);
            }
        });

        s15.setBackground(new java.awt.Color(255, 255, 255));
        s15.setToolTipText("load the specimen");
        s15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s15.setOpaque(true);
        s15.setPreferredSize(new java.awt.Dimension(91, 48));
        s15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s15MouseClicked(evt);
            }
        });

        s14.setBackground(new java.awt.Color(255, 255, 255));
        s14.setToolTipText("load the specimen");
        s14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s14.setOpaque(true);
        s14.setPreferredSize(new java.awt.Dimension(91, 48));
        s14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s14MouseClicked(evt);
            }
        });

        s13.setBackground(new java.awt.Color(255, 255, 255));
        s13.setToolTipText("load the specimen");
        s13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s13.setOpaque(true);
        s13.setPreferredSize(new java.awt.Dimension(91, 48));
        s13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s13MouseClicked(evt);
            }
        });

        s12.setBackground(new java.awt.Color(255, 255, 255));
        s12.setToolTipText("load the specimen");
        s12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s12.setOpaque(true);
        s12.setPreferredSize(new java.awt.Dimension(91, 48));
        s12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s12MouseClicked(evt);
            }
        });

        s11.setBackground(new java.awt.Color(255, 255, 255));
        s11.setToolTipText("load the specimen");
        s11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        s11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        s11.setOpaque(true);
        s11.setPreferredSize(new java.awt.Dimension(91, 48));
        s11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s11MouseClicked(evt);
            }
        });

        img1.setText("1");

        img2.setText("2");

        img3.setText("3");

        img4.setText("4");

        img5.setText("5");

        img6.setText("6");

        img7.setText("7");

        img8.setText("8");

        img9.setText("9");

        img10.setText("10");

        img11.setText("11");

        img12.setText("12");

        img13.setText("13");

        img14.setText("14");

        img15.setText("15");

        jLabel3.setText("SAMPLE SPECIMENS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(img15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(29, 29, 29)
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(s6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(img6)))
                                                    .addComponent(img5)))
                                            .addComponent(img4))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(s7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(img7)))
                                    .addComponent(img3))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(img8)))
                            .addComponent(img2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img9)))
                    .addComponent(img1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img10))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img11))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img12))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img13))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img14))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img15))
                .addContainerGap(893, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void breakAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakAnalyzeActionPerformed
        // TODO add your handling code here:
        if(captchaPresent)
       {
         // if(guiFirst)
          //{
           m=new Main(imgInfo);
           recognizedCAPTCHA=m.backEnd(website,originalImage);
           AnalyzeCaptcha c=new AnalyzeCaptcha();
           c.setVisible(true);
           c.saveContents(website,file1);
           c.setComponents(m);
       }
        else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_breakAnalyzeActionPerformed
    /*
    *This method loads the FileDialog to browse and select captcha image to break
    */
    private void loadImage() throws IOException
    {
        
        if(captchaPresent)
        {
            Dimension d=getScaledDimension(imgSize, boundary);
//            BufferedImage m=ImageIO.read(file1);
//            Image his=new Scale().scale_img(m,d.width,d.height);f
//            history.setIcon(new ImageIcon(his));  
             his=originalImage;
            Image his2=Scale.scale_img(originalImage,d.width,d.height);
            history.setIcon(new ImageIcon(his2));
            
           
        }
        fileDialog=new JFileChooser();
       website=websiteSelect.getSelectedItem().toString();
       
        //System.out.println(website);
       fileDialog.setCurrentDirectory(new java.io.File("ImgDatabase\\"+website));
        int returnVal = fileDialog.showOpenDialog(this);
        
       
	            if (returnVal == JFileChooser.APPROVE_OPTION) 
	            {

                         file1 = fileDialog.getSelectedFile();
                        
                        try 
                        {
                           // image1.setIcon(new ImageIcon(ImageIO.read(file1)));
                            
                             originalImage=ImageIO.read(file1);
                             
                             image1.setIcon(new ImageIcon(Scale.scale_img(originalImage,280,117)));
                            captchaPresent=true;
                        } 
                   catch (Exception e1) 
                   {
                      
                        JOptionPane.showMessageDialog(rootPane, "can't read input file", null, JOptionPane.ERROR_MESSAGE);
                   }
	               
	            }
                  
//                    else if(returnVal==JFileChooser.CANCEL_OPTION){
//                        
////	               statusLabel.setText("Open command cancelled by user." );           
//	            }
//                    
                    fileDialog=null;//memory deaallocation
    }
    /*
    *called when Website name is selected
    */
    private void websiteSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_websiteSelectItemStateChanged
        // TODO add your handling code here:  
        //System.out.println("Item event");
        
        website=websiteSelect.getSelectedItem().toString();
        try
        {
            setGallery();
        }
        catch(Exception e)
        {
             if(!website.equals("--------Select Website--------"))
                           
                JOptionPane.showMessageDialog(rootPane, "can't read input file", null, JOptionPane.ERROR_MESSAGE);
        }
//               try {
//                specimen1.setIcon(new ImageIcon(ImageIO.read(new java.io.File("D:\\ImgDatabase\\Old\\CAPTCHA   without  noise\\addhar - 25\\2.jpg"))));
//            } catch (IOException ex) {
//                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
    }//GEN-LAST:event_websiteSelectItemStateChanged
 /*
  *This method populates the sample specimens with images of selected 
  */
   public void setGallery() throws IOException
   {
       
       path="ImgDatabase\\"+website;
       File dir=new File(path);//main directory for images
        fList = dir.listFiles();//get list of all files 
        
//       if
//               (website.equals("ESCHOLARSHIP")||website.equals("SHIKSHA"))
//       {
//           extension="jpeg";
//       }
//       else if(website.equals("CITYALLY")||website.equals("SPEAKINGTREE")||website.equals("WEBSPAMPROTECT")||website.equals("WIKIPEDIA"))
//       {
//           extension="png";
//       }
//       else 
//       {
//           extension="jpg";
//       }
//      
      //renameFiles();
        dir=null;//memory deallocation
        specimenLoaded=true;
       dimensionAdjustment(fList);
   }
   /*
   *This method renames files serially like 1 2 3 4
   */
   public void renameFiles() throws IOException
   {
       File directory=new File(path);
        fList = directory.listFiles();
        //System.out.println("The length is "+directory.listFiles().length);
         for (File file : fList){
//            if (file.isFile())
//            {
//               int k = file.getName().lastIndexOf('.');
//
//    extension = file.getName().substring(k+1);
//    System.out.println("extension"+extension);
                try{
                    //System.out.println(file.getName());
                int a=Integer.parseInt(file.getName().replaceFirst("[.][^.]+$", ""));
                if(a>15)
                    throw new Exception();
                }
                catch(Exception e)
                {
                    //System.out.println("In exception file:  "+file.getName());
                    for(int i=1;i<16;i++)
                    {
                        boolean success=file.renameTo(new File(path+"\\"+i+"."+extension));
                      //   System.out.println("i="+i+"\nsuccess: "+success);
                        if(success)
                        {
                            //System.out.println("File renamed");
                            break;
                        }
                       
                        
                    }
                }
            }
   }
  /*
   *This method calls the getScaledDimension() method for each label  to adjust the dimension of the image to fit in sample specimen
   */ 
  public void dimensionAdjustment(File[] files) throws IOException
   {
       
            //JLabel[] labels ={jLabel3,jLabel5,jLabel4,jLabel6,jLabel7,jLabel8,jLabel9,jLabel10,jLabel11,jLabel12,jLabel17,jLabel14,jLabel13,jLabel16,jLabel17};
            JLabel[] labels =  {s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15};
//        File file2;
//        file2 = new File(path);


        
          //BufferedImage originalImage;
           for(int i=0;i<15;i++)
           {
          
           
               //Fil.e file3=new File(file2+"\\"+i+"."+extension);
               //System.out.println(file3.getAbsoluteFile());
               try
               {
                temp=ImageIO.read(files[i]);
               }
               catch(IOException e)
               {}
                if(i==0)
                {
                    imgSize=new Dimension(temp.getWidth(),temp.getHeight());
                    newDimensions=getScaledDimension(imgSize,boundary);
                }
                 resizedImage=Scale.scale_img(temp,newDimensions.width,newDimensions.height);
                 labels[i].setIcon(new ImageIcon(resizedImage));
               
           }
   }
  /*
  *This method adjusts the dimension of the image to fit the dimensions of the label
  */
   public static Dimension getScaledDimension(Dimension imgSize, Dimension boundary) {

    int original_width = imgSize.width;
    int original_height = imgSize.height;
    int bound_width = boundary.width;
    int bound_height = boundary.height;
    int new_width = original_width;
    int new_height = original_height;

    // first check if we need to scale width
    if (original_width > bound_width) {
        //scale width to fit
        new_width = bound_width;
        //scale height to maintain aspect ratio
        new_height = (new_width * original_height) / original_width;
    }

    // then check if we need to scale even with the new height
    if (new_height > bound_height) {
        //scale height to fit instead
        new_height = bound_height;
        //scale width to maintain aspect ratio
        new_width = (new_height * original_width) / original_height;
    }

    return new Dimension(new_width, new_height);
}
    private void image1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image1MouseClicked
//      ImageIcon yourImage=(ImageIcon)image.getIcon();
//      Image image = yourImage.getImage();
//      BufferedImage buffered = (BufferedImage) image;
//        Image im=new Scale().scale_img(buffered,imgSize.width,imgSize.height);
//        image.setIcon(new ImageIcon(ImageIO.read(im)));
       
    }//GEN-LAST:event_image1MouseClicked

    private void s1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseClicked
        // TODO add your handling code here:   
       
        if(specimenLoaded)
            specimenToOriginal(fList[0]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
        
    }//GEN-LAST:event_s1MouseClicked
/*
    *This method transforms the image in sample specimens to the original Label displayed in center
    */
    private void specimenToOriginal(File fileImage)
    {
        //Dimension d2=new Dimension(210,93);
          if(captchaPresent)
        {
            Dimension d=getScaledDimension(imgSize,boundary);
           // BufferedImage m = null;
//              try {
//                 // m = ImageIO.read(fileImage);
//                 // historyPath=file1.getAbsolutePath();
//              } catch (IOException ex) 
//              {
//                   JOptionPane.showMessageDialog(rootPane, "can't read input file", null, JOptionPane.ERROR_MESSAGE);
//                  Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
//              }
            his=originalImage;
            Image his2=Scale.scale_img(originalImage,d.width,d.height);
            history.setIcon(new ImageIcon(his2));
           
        }
//        file1=new File(path+"\\"+img.getText()+"."+extension);
//     
                    try 
                        {
                            originalImage=ImageIO.read(fileImage);
                             image1.setIcon(new ImageIcon(Scale.scale_img(originalImage,280,117)));
                            captchaPresent=true;
                        } 
                   catch (IOException e1) 
                   {
                        JOptionPane.showMessageDialog(rootPane, "can't read input file", null, JOptionPane.ERROR_MESSAGE);
                   }
                    
    }
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void websiteSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_websiteSelectActionPerformed

        
         try {
              website=websiteSelect.getSelectedItem().toString();
             CommonUtilityClass util=new CommonUtilityClass();
              if(!website.equals("--------Select Website--------"))
            util.readDATFile("DATfiles\\"+website+".dat");
        } catch (IOException ex) {
            if(!website.equals("--------Select Website--------"))
            {
            JOptionPane.showMessageDialog(rootPane, "can't load dat file", null, JOptionPane.ERROR_MESSAGE);
            //System.exit(0);
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_websiteSelectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(website==null||website.equals("--------Select Website--------"))
        {
            JOptionPane.showMessageDialog(rootPane, "Please select website name", null, JOptionPane.ERROR_MESSAGE); 
        }
        else
        {
         try {
            loadImage();
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            setGallery();
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        }// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void s2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s2MouseClicked
       if(specimenLoaded)
            specimenToOriginal(fList[1]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_s2MouseClicked

    private void s3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s3MouseClicked
    if(specimenLoaded)
            specimenToOriginal(fList[2]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_s3MouseClicked

    private void s4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s4MouseClicked
       if(specimenLoaded)
            specimenToOriginal(fList[3]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_s4MouseClicked

    private void s5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s5MouseClicked
  if(specimenLoaded)
            specimenToOriginal(fList[4]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_s5MouseClicked

    private void s6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s6MouseClicked
      if(specimenLoaded)
            specimenToOriginal(fList[5]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_s6MouseClicked

    private void s7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s7MouseClicked
       if(specimenLoaded)
            specimenToOriginal(fList[6]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_s7MouseClicked

    private void s8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s8MouseClicked
         if(specimenLoaded)
            specimenToOriginal(fList[7]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_s8MouseClicked

    private void s9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s9MouseClicked
        if(specimenLoaded)
            specimenToOriginal(fList[8]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_s9MouseClicked

    private void s10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s10MouseClicked
       if(specimenLoaded)
            specimenToOriginal(fList[9]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_s10MouseClicked

    private void s11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s11MouseClicked
        if(specimenLoaded)
            specimenToOriginal(fList[10]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_s11MouseClicked

    private void s12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s12MouseClicked
        if(specimenLoaded)
            specimenToOriginal(fList[11]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_s12MouseClicked

    private void s13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s13MouseClicked
        if(specimenLoaded)
            specimenToOriginal(fList[12]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_s13MouseClicked

    private void s14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s14MouseClicked
         if(specimenLoaded)
            specimenToOriginal(fList[13]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_s14MouseClicked

    private void s15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s15MouseClicked
        if(specimenLoaded)
            specimenToOriginal(fList[14]);
         else
       {
           JOptionPane.showMessageDialog(rootPane, "captcha image not loaded", null, JOptionPane.ERROR_MESSAGE);
       }
  
        // TODO add your handling code here:
    }//GEN-LAST:event_s15MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseClicked

       if(originalImage==null|| his==null)
       {
          JOptionPane.showMessageDialog(rootPane, "History is empty", null, JOptionPane.ERROR_MESSAGE);
       }
       else{
       //  try 
                       // {
                            //File file3=new File(historyPath);
                            originalImage=his;
                            image1.setIcon(new ImageIcon(Scale.scale_img(originalImage,280,117)));
//                            file1=file3;
                            captchaPresent=true;
                       // } 
//                   catch (IOException e1) 
//                   {
//                         JOptionPane.showMessageDialog(rootPane, "can't read input file", null, JOptionPane.ERROR_MESSAGE);
//
//                   }
       }// TODO add your handling code here:
    }//GEN-LAST:event_historyMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

        JOptionPane.showMessageDialog(rootPane, "This software is for ethical hacking and awareness creation\nShould not be reverse engineered\nNot to be used for hacking purpose\nShould not decompose code by decomposing the software\n\n \u00a9 CAT engineering","CAPTCHA Analyzer tool", WIDTH);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Help h=new Help();
h.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

  
//   @Override
//    public void itemStateChanged(ItemEvent i)
//    {
//        website=websiteSelect.getSelectedItem().toString();
//    }
//    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton breakAnalyze;
    private javax.swing.JLabel history;
    private javax.swing.JLabel image;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img10;
    private javax.swing.JLabel img11;
    private javax.swing.JLabel img12;
    private javax.swing.JLabel img13;
    private javax.swing.JLabel img14;
    private javax.swing.JLabel img15;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel img7;
    private javax.swing.JLabel img8;
    private javax.swing.JLabel img9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s10;
    private javax.swing.JLabel s11;
    private javax.swing.JLabel s12;
    private javax.swing.JLabel s13;
    private javax.swing.JLabel s14;
    private javax.swing.JLabel s15;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JLabel s6;
    private javax.swing.JLabel s7;
    private javax.swing.JLabel s8;
    private javax.swing.JLabel s9;
    private javax.swing.JComboBox websiteSelect;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}